sudo: false
dist: trusty

env:
  - PROTOBUF_VERSION=3.0.0-beta-2

language: rust

rust:
  - stable
  - beta
  - nightly

#addons:
#  apt:
#    packages:
#    - protobuf-compiler

script:
  - rustc --version
  - ./test.sh
  - ./install-protobuf.sh
  - cargo install protobuf
  - ./gen-rs.sh
  - ./build-all.sh

notifications:
  email:
    on_success: never

# vim: set ts=2 sw=2 et:
