sudo: false
dist: trusty

env:
  - PROTOBUF_VERSION=3.1.0

language: rust

rust:
  - stable
  - beta
  - nightly

#addons:
#  apt:
#    packages:
#    - protobuf-compiler

script:
  - rustc --version
  - ./test.sh
  - ./install-protobuf.sh
  - cargo install protobuf
  - ./grpc-compiler/test-protoc-plugin/gen.sh
  - cargo check --all

notifications:
  email:
    on_success: never

# vim: set ts=2 sw=2 et:
